version: "3.7"

services:
  app:
    build:
      target: production
    env_file:
      - .env.prod

    # It is best practice, sometimes that docker crashes, 
    # it will be started automatically
    restart: always 
    
    command: npm run start
