version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    # TODO: Have different command to run service in development and production
    # command: npm run dev
    command: npm run start:dev
