@startuml DomainModel

class FriendInCrime
class User
class Profile
class Plan
class Atendee
class Name
class Conversation

FriendInCrime --> "2..n" User
User *--> Profile
User o--> Plan

Profile *--> Name

Plan --> Conversation
Plan "0..n" o-down-> Atendee

Atendee -up-|> User

@enduml