@startuml

' TODO: Make my own diagram
 
state INITIAL
state requested
state REGISTRATION
state reading
state registered

[*] --> INITIAL
INITIAL --> requested : User requests to register
requested --> REGISTRATION : System shows registration form 
REGISTRATION --> reading : User fill form
reading --> INITIAL : System rejects registration (non-valid form)
reading --> registered : System register valid user
registered --> [*]

@enduml